# Base image
FROM node:18

WORKDIR /app/microservices/database-microservice

RUN npm install ts-node

COPY microservices/database-microservice/package*.json ./

RUN npm clean-install

COPY microservices/database-microservice .

WORKDIR /app/interfaces

COPY interfaces .

WORKDIR /app/microservices/database-microservice

CMD npm run start:dev