# Base image
FROM node:18

WORKDIR /app/microservices/mailer-microservice

RUN npm install ts-node

COPY microservices/mailer-microservice/package*.json ./

RUN npm install ts-node

RUN npm clean-install

COPY microservices/mailer-microservice .

WORKDIR /app/interfaces

COPY interfaces .

WORKDIR /app/microservices/mailer-microservice

CMD npm run start:dev