# Base image
FROM node:18

WORKDIR /app

COPY microservices/controller-microservice/package*.json ./

RUN npm clean-install

COPY microservices/controller-microservice .

WORKDIR /app/interfaces

COPY interfaces .

WORKDIR /app/microservices/controller-microservice

CMD npm run start:dev