# Base image
FROM node:18

WORKDIR /app/microservices/cron-microservice

RUN npm install ts-node

COPY microservices/cron-microservice/package*.json ./

RUN npm install ts-node

RUN npm clean-install

COPY microservices/cron-microservice .

WORKDIR /app/interfaces

COPY interfaces .

WORKDIR /app/microservices/cron-microservice

CMD npm run start:dev